version = "1.0"

[main]
name = "My Webapp configuration"

    [main.sftp]
    name = "SFTP access"

        [main.sftp.with_sftp]
        ask = "Do you need a SFTP access?"
        type = "boolean"
        default = true

        [main.sftp.password]
        ask = "Set a password for the SFTP access"
        type = "password"
        optional = true
        visible = "with_sftp"
        help = "If a password already exist, leave blank and it will not be replaced."

    [main.php_fpm_config]
    name = "PHP-FPM configuration"

        [main.php_fpm_config.phpversion]
        ask = "PHP version"
        type = "select"
        choices = ["none", "7.3", "7.4", "8.0"]
        default = "none"

# TODO: Add protected_path as tags, which are created as permission "label (path)", so admin can protect a specific path
#    [main.permissions]
#        [main.permissions.proteced_path]
#        ask = "Protected path"
#        help = "A permission will be created so you can restrict the access to a subpath of the web app."
#        type = "tags"
    