test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.with_sftp = "1"
	args.phpversion="7.4"
	args.with_mysql=1