test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.with_sftp = "1"
	args.phpversion = "7.4"
	args.with_mysql = "1"

[7.3_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "7.3"

[8.0_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "8.0"

[8.1_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "8.1"

[8.2_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "8.2"
