test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.with_sftp = "1"
	args.phpversion = "7.4"
	args.with_mysql = "1"

[73_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "7.3"

[80_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "8.0"

[81_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "8.1"

[82_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "8.2"
